import { NeedOrSalePost, ServiceProviderPost, ShopPost } from "@/types";

export const SELL_SAMPLES: NeedOrSalePost[] = [
  { id: "s_plot", userId: "admin_9994837342", type: "SELL", title: "2400 Sqft CMDA Plot — Vallam", raw_text: "", description: "DTCP approved residential plot with 30ft road frontage. Ready to build.", category: "Plots & Real Estate", area_tag: "Vallam", price: "2450000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "s_house", userId: "admin_9994837342", type: "SELL", title: "2 BHK House for Rent", raw_text: "", description: "Modular kitchen, 2 bathrooms, 24/7 Kaveri water, car parking available.", category: "Property Rental", area_tag: "Medical College Road", price: "12500", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "s_bike", userId: "admin_9994837342", type: "SELL", title: "Hero Splendor 2022 — Single Owner", raw_text: "", description: "65+ kmpl mileage, clean papers, original condition.", category: "Used Vehicles", area_tag: "New Bus Stand", price: "68000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "s_iphone", userId: "admin_9994837342", type: "SELL", title: "iPhone 13 128GB Blue", raw_text: "", description: "Mint condition, original box, charger & bill available.", category: "Electronics & Mobiles", area_tag: "Old Bus Stand", price: "42000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "s_sofa", userId: "admin_9994837342", type: "SELL", title: "Teakwood 5-Seater Sofa Set", raw_text: "", description: "Premium finish, comfortable cushions, well maintained.", category: "Household Goods", area_tag: "Karanthai", price: "18500", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
];

export const NEED_SAMPLES: NeedOrSalePost[] = [
  { id: "n_land", userId: "admin_9994837342", type: "NEED", title: "Need 1-2 Acres Commercial Land", raw_text: "", description: "Main road facing land near New Bus Stand or Vallam for warehouse use.", category: "Plots & Real Estate", area_tag: "Vallam", price: "5000000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "n_apt", userId: "admin_9994837342", type: "NEED", title: "2 BHK Apartment near Medical College", raw_text: "", description: "Needed urgently. Budget ₹10,000/month. Preferred ground floor.", category: "Property Rental", area_tag: "Medical College Road", price: "10000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "n_laptop", userId: "admin_9994837342", type: "NEED", title: "Need Used Laptop under ₹25,000", raw_text: "", description: "i5 8th gen or above, 8GB RAM minimum, good battery backup.", category: "Electronics & Mobiles", area_tag: "Tanjore Town (General)", price: "25000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "n_tractor", userId: "admin_9994837342", type: "NEED", title: "Need Used Mini Tractor", raw_text: "", description: "For paddy field cultivation near Kumbakonam Road. Any brand.", category: "Used Vehicles", area_tag: "Vallam", price: "350000", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
  { id: "n_cook", userId: "admin_9994837342", type: "NEED", title: "Need Cook for Functions — Tanjore", raw_text: "", description: "Brahmin style catering needed for 200 guests marriage function.", category: "General Requirement", area_tag: "Tanjore Town (General)", price: "0", phone: "9994837342", is_verified: true, created_at: new Date() as any, expires_at: new Date(Date.now() + 30 * 86400000) as any },
];

export const SERVICE_SAMPLES: ServiceProviderPost[] = [
  { id: "sv_elec", userId: "admin_9994837342", name: "Senthil Kumar — Home Electrician", skill_category: "Electrician", experience: "8+ Years", area_tag: "Tanjore Town (General)", phone: "9994837342", rating: 4.9, description: "Expert house wiring, DB box installation, inverter assembly, three-phase connections.", is_verified: true, created_at: new Date() as any },
  { id: "sv_plumb", userId: "admin_9994837342", name: "Rajesh K — Expert Plumber", skill_category: "Plumber", experience: "6+ Years", area_tag: "Medical College Road", phone: "9994837342", rating: 4.8, description: "Pipe fitting, water tank washing, Kaveri line tap connections, motor pump installation.", is_verified: true, created_at: new Date() as any },
  { id: "sv_ac", userId: "admin_9994837342", name: "Muthu Cool Tech — AC & Fridge", skill_category: "AC & Fridge Repair", experience: "7+ Years", area_tag: "Old Bus Stand", phone: "9994837342", rating: 4.9, description: "Split AC gas filling, deep foam wash, refrigerator compressor repairs.", is_verified: true, created_at: new Date() as any },
  { id: "sv_carp", userId: "admin_9994837342", name: "Venu Gopal — Wood Architect", skill_category: "Carpenter", experience: "10+ Years", area_tag: "South Rampart (Thenkeezh Street)", phone: "9994837342", rating: 5.0, description: "Modular kitchen woodworks, door laminations, bespoke wardrobes & furniture.", is_verified: true, created_at: new Date() as any },
  { id: "sv_paint", userId: "admin_9994837342", name: "Murugan Professional Painters", skill_category: "Painter", experience: "12+ Years", area_tag: "Vallam", phone: "9994837342", rating: 4.8, description: "Interior & exterior wall painting, waterproof putty, Asian Paints wall texture.", is_verified: true, created_at: new Date() as any },
];

export const SHOP_SAMPLES: ShopPost[] = [
  { id: "sh_glen", userId: "admin_9994837342", shop_name: "GLEN Exclusive Gallery", category: "Electronics & Mobiles", address_text: "New Busstand Road, Thanjavur", landmark: "Near New Bus Stand", hours: "9:30 AM – 9 PM", phone: "9994837342", area_tag: "New Bus Stand", offer_title: "Up to 60% OFF — Grand Opening Sale", offer_description: "Massive discounts on kitchen chimneys, hobs, cooktops & gas stoves.", image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop", latitude: 10.7852, longitude: 79.1162, is_claimed: true, created_at: new Date() as any },
  { id: "sh_coffee", userId: "admin_9994837342", shop_name: "Tanjore Degree Coffee & Sweets", category: "Cafe & Restaurant", address_text: "South Rampart Road, Tanjore Town", landmark: "Near Big Temple South Gate", hours: "6 AM – 10 PM", phone: "9994837342", area_tag: "South Rampart (Thenkeezh Street)", offer_title: "Free Filter Coffee with Halwa Purchase", offer_description: "1 complimentary brass tumbler filter coffee on purchasing 250g Tirunelveli Halwa.", image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&auto=format&fit=crop", latitude: 10.7858, longitude: 79.1285, is_claimed: true, created_at: new Date() as any },
  { id: "sh_silk", userId: "admin_9994837342", shop_name: "Thanjavur Silk Handloom House", category: "Textiles & Readymades", address_text: "Karanthai Main Road, Thanjavur", landmark: "Opposite Karandhai Tamil Sangam", hours: "9 AM – 9 PM", phone: "9994837342", area_tag: "Karanthai", offer_title: "Flat 25% OFF Wedding Pure Zari Silks", offer_description: "Direct handloom weavers price. Flat 25% off Kanchipuram & Thanjavur pure silk sarees.", image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop", latitude: 10.8095, longitude: 79.1415, is_claimed: true, created_at: new Date() as any },
  { id: "sh_gold", userId: "admin_9994837342", shop_name: "Ponniyin Selvan Gold Palace", category: "Gold & Jewelry", address_text: "Gandhiji Road, Thanjavur", landmark: "Near Old Bus Stand Signal", hours: "10 AM – 8 PM", phone: "9994837342", area_tag: "Gandhiji Road", offer_title: "Zero Making Charges — Akshaya Tritiya", offer_description: "Zero wastage zero making charge on all 916 hallmark gold jewellery today.", image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop", latitude: 10.7892, longitude: 79.1388, is_claimed: true, created_at: new Date() as any },
  { id: "sh_pharma", userId: "admin_9994837342", shop_name: "Sri Murugan Medical & Pharmacy", category: "Medical & Pharmacy", address_text: "Medical College Road, Thanjavur", landmark: "Opposite MGMGH Gate", hours: "8 AM – 10 PM", phone: "9994837342", area_tag: "Medical College Road", offer_title: "15% OFF on Generic Medicines", offer_description: "Flat 15% discount on all Jan Aushadhi generic medicines available stock.", image_url: "https://images.unsplash.com/photo-1586015555751-63c2057d59b2?w=600&auto=format&fit=crop", latitude: 10.7601, longitude: 79.1135, is_claimed: true, created_at: new Date() as any },
];
